apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: traefik
spec:
  serviceRef:
    name: traefik
    port: 443
  targetType: ip
  targetGroupARN: {{ .Values.targetGroupArn }}
