aws-load-balancer-controller:
  replicaCount: 2

  serviceAccount:
    name: aws-load-balancer-controller

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 128Mi

  topologySpreadConstraints:
    - topologyKey: "topology.kubernetes.io/zone"
      maxSkew: 1
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: aws-load-balancer-controller
          app.kubernetes.io/instance: aws-load-balancer-controller
    - topologyKey: "kubernetes.io/hostname"
      maxSkew: 1
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: aws-load-balancer-controller
          app.kubernetes.io/instance: aws-load-balancer-controller

  createIngressClassResource: false
  ingressClassParams:
    create: false

  disableIngressClassAnnotation: true
