apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bucket-lister
  name: bucket-lister
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: bucket-lister
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bucket-lister
    spec:
      containers:
        - name: bucket-lister
          image: ghcr.io/johanvandeweerd/bucket-lister:20241114173745-3104cbf
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
      serviceAccountName: bucket-lister
