apiVersion: eks.services.k8s.aws/v1alpha1
kind: PodIdentityAssociation
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
  labels:
    app: bucket-lister
  name: bucket-lister
spec:
  clusterName: {{ .Values.projectName }}
  namespace: default
  roleARN: {{ .Values.roleArn }}
  serviceAccount: bucket-lister
