apiVersion: eks.services.k8s.aws/v1alpha1
kind: PodIdentityAssociation
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    app: bucket-lister
  name: bucket-lister
spec:
  clusterName: {{ .Values.projectName }}
  namespace: default
  roleARN: {{ .Values.roleArn }}
  serviceAccount: bucket-lister
