apiVersion: v1
kind: Service
metadata:
  labels:
    app: bucket-lister
  name: bucket-lister
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: bucket-lister
  type: ClusterIP