apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: bucket-lister
  name: sleep
spec:
  template:
    spec:
      containers:
        - command:
            - sleep
            - "1"
          image: alpine
          name: sleep
      restartPolicy: Never
