apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: argocd
  namespace: argocd
spec:
  provider:
    aws:
      region: ${awsRegion}
      role: arn:aws:iam::${awsAccountId}:role/${clusterName}-argocd
      service: SecretsManager
