karpenter:
  revisionHistoryLimit: 1
  dnsPolicy: Default
  controller:
    resources:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 250m
        memory: 500Mi
  topologySpreadConstraints:
    - topologyKey: "topology.kubernetes.io/zone"
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      minDomains: 3
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: karpenter
    - topologyKey: "kubernetes.io/hostname"
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: karpenter
