apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-telemetry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/johan-vandeweerd-hs/cluster-playground
    path: applications/open-telemetry-collectors
    targetRevision: obi
    helm:
      valuesObject:
        ${indent(8, yamlencode(valuesObject))}
  destination:
    server: ${clusterArn}
    namespace: open-telemetry
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
