eks-chart:
  fullnameOverride: ack-eks

  deployment:
    replicas: 2

  metrics:
    service:
      create: true

  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 64Mi

  resourceTags:
    - services.k8s.aws/controller-version=%CONTROLLER_SERVICE%-%CONTROLLER_VERSION%
    - services.k8s.aws/namespace=%K8S_NAMESPACE%

  leaderElection:
    enabled: true
