external-dns:
  revisionHistoryLimit: 0

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 128Mi

  topologySpreadConstraints:
    - topologyKey: "topology.kubernetes.io/zone"
      maxSkew: 1
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: external-dns
          app.kubernetes.io/instance: external-dns
    - topologyKey: "kubernetes.io/hostname"
      maxSkew: 1
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: external-dns
          app.kubernetes.io/instance: external-dns

  serviceMonitor:
    enabled: true

  logFormat: json
