apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simple
spec:
  mode: deployment
  imagePullPolicy: Always
  managementState: managed
  podDisruptionBudget:
    maxUnavailable: 1
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      memory: 500Mi
  autoscaler:
    minReplicas: 2
    maxReplicas: 5
  serviceAccount: open-telemetry
  config: |
    receivers:
      awscloudwatch:
        region: {{ .Values.awsRegion }}
        logs:
          poll_interval: 1m
          groups:
            named:
              /aws/eks/{{ .Values.clusterName }}/cluster:
                prefixes:
                  - authenticator
                  - kube-apiserver
    processors:
    exporters:
      debug:
    service:
      pipelines:
        logs:
          receivers:
            - awscloudwatch
          processors: []
          exporters:
            - debug
