external-secrets:
  fullnameOverride: "external-secrets"
  image:
    repository: ghcr.io/external-secrets/external-secrets
    pullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      memory: 128Mi
  #leaderElect: false
  #replicaCount: 1
  revisionHistoryLimit: 0
  serviceAccount:
    create: true

  webhook:
    #  nameOverride: ""
    #  fullnameOverride: ""
    image:
      repository: ghcr.io/external-secrets/external-secrets
      pullPolicy: Always
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        memory: 128Mi
    #replicaCount: 1
    revisionHistoryLimit: 0
    certManager:
      enabled: false

  certController:
    #  nameOverride: ""
    #  fullnameOverride: ""
    image:
      repository: ghcr.io/external-secrets/external-secrets
      pullPolicy: Always
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        memory: 128Mi
    #replicaCount: 1
    revisionHistoryLimit: 0
