apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: open-telemetry
spec:
  exporter:
    endpoint: http://open-telemetry-debug-collector.open-telemetry:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
