apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: httpbin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: kong/httpbin
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
