apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: httpbin
  name: httpbin
spec:
  ingressClassName: ingress
  rules:
    - host: httpbin.{{ .Values.projectName }}.hackathon.hootops.com
      http:
        paths:
          - backend:
              service:
                name: httpbin
                port:
                  name: http
            pathType: Prefix
            path: /
