apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - patch
