apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd
subjects:
  - kind: ServiceAccount
    name: argocd
    namespace: argocd
roleRef:
  kind: Role
  name: argocd
  apiGroup: rbac.authorization.k8s.io
