apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  instanceProfile: {{ .Values.karpenter.settings.clusterName }}-karpenter-node
  amiFamily: Bottlerocket
  subnetSelectorTerms:
    - tags:
        Name: {{ .Values.karpenter.settings.clusterName }}-private-*
  securityGroupSelectorTerms:
    - tags:
        Name: eks-cluster-sg-{{ .Values.karpenter.settings.clusterName }}-*
