apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${name}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${gitUrl}
    path: modules/platform/${name}/chart
    targetRevision: ${revision}
    helm:
      valueFiles:
        - values.yaml
      parameters: %{ if length(helm_parameters) == 0 }[]%{endif}
%{ for key, value in helm_parameters ~}
        - name: "${key}"
          value: "${value}"
%{ endfor ~}
  destination:
    namespace: ${namespace}
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
