traefik:
  image:
    pullPolicy: Always

  deployment:
    revisionHistoryLimit: 0

  ingressClass:
    enabled: true
    isDefaultClass: true
    name: ingress

  providers:
    kubernetesCRD:
      enabled: false
    kubernetesIngress:
      enabled: true
      ingressClass: ingress

  ports:
    web:
      forwardedHeaders:
        insecure: true
    websecure:
      forwardedHeaders:
        insecure: true

  logs:
    general:
      format: json
      level: "INFO"
      noColor: true
    access:
      enabled: true
      format:  json

  additionalArguments:
    # Allow accessing the dashboard at http://localhost:9000/dashboard/ when using port-forward
    - --api.insecure=true
    # Skip TLS verification for backends with self-signed certificates
    - --serversTransport.insecureSkipVerify=true

  service:
    enabled: true
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      memory: 100Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
