name: Build and push bucket-lister image to ghcr.io

on:
  push:
    branches: [ "master" ]
    paths:
      - 'images/bucket-lister/**'
      - '.github/workflows/bucket-lister.yaml'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date and short git SHA as env variable
        id: tag
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "build_date_time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "short_git_sha=${GITHUB_SHA:1:7}" >> $GITHUB_OUTPUT

      - name: Log in to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: images/bucket-lister
          tags: ghcr.io/${{ github.repository_owner }}/bucket-lister:${{ steps.tag.outputs.build_date_time }}-${{ steps.tag.outputs.short_git_sha }}
          push: true
          platforms: linux/amd64,linux/arm64
